defaults:
  - _self_
  - dataset: mnist.yaml
  - model: lenet5.yaml
  - transform: albumentations.yaml

save_path: model/
cuda: True
seed: null
batch_size: 128
epochs: 50

hydra:
  job:
    chdir: True
